In [1]:
import nltk
nltk.download()
#nltk.download('punkt')


showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [2]:
paragraph="""John had always been fascinated by technology. Ever since he was a child, he dreamed of becoming a software engineer. After years of studying and hard work, he finally landed a job at a well-known tech company, TechCorp. His first project was to develop an AI-based system that could analyze customer feedback and provide real-time insights. Excited and nervous at the same time, John knew this was the opportunity he had been waiting for."

"One day, while taking a break, John met Lisa, a data scientist who specialized in machine learning. They quickly bonded over their shared passion for AI and robotics. Together, they brainstormed innovative ideas that could revolutionize the company's products. Their combined efforts soon paid off, as their AI system became one of the company's top-performing tools."

"As months passed, John found himself thinking more about starting his own tech startup. He knew the risks involved but felt that the potential rewards far outweighed them. With Lisa's encouragement and the support of a few close colleagues, John decided to take the leap and begin his entrepreneurial journey."""

In [6]:
sentences = nltk.sent_tokenize(paragraph)
print(sentences)
print(len(sentences))

['John had always been fascinated by technology.', 'Ever since he was a child, he dreamed of becoming a software engineer.', 'After years of studying and hard work, he finally landed a job at a well-known tech company, TechCorp.', 'His first project was to develop an AI-based system that could analyze customer feedback and provide real-time insights.', 'Excited and nervous at the same time, John knew this was the opportunity he had been waiting for."', '"One day, while taking a break, John met Lisa, a data scientist who specialized in machine learning.', 'They quickly bonded over their shared passion for AI and robotics.', "Together, they brainstormed innovative ideas that could revolutionize the company's products.", 'Their combined efforts soon paid off, as their AI system became one of the company\'s top-performing tools."', '"As months passed, John found himself thinking more about starting his own tech startup.', 'He knew the risks involved but felt that the potential rewards far 

In [7]:
words = nltk.word_tokenize(paragraph)
print(words)
print(len(words))

['John', 'had', 'always', 'been', 'fascinated', 'by', 'technology', '.', 'Ever', 'since', 'he', 'was', 'a', 'child', ',', 'he', 'dreamed', 'of', 'becoming', 'a', 'software', 'engineer', '.', 'After', 'years', 'of', 'studying', 'and', 'hard', 'work', ',', 'he', 'finally', 'landed', 'a', 'job', 'at', 'a', 'well-known', 'tech', 'company', ',', 'TechCorp', '.', 'His', 'first', 'project', 'was', 'to', 'develop', 'an', 'AI-based', 'system', 'that', 'could', 'analyze', 'customer', 'feedback', 'and', 'provide', 'real-time', 'insights', '.', 'Excited', 'and', 'nervous', 'at', 'the', 'same', 'time', ',', 'John', 'knew', 'this', 'was', 'the', 'opportunity', 'he', 'had', 'been', 'waiting', 'for', '.', "''", '``', 'One', 'day', ',', 'while', 'taking', 'a', 'break', ',', 'John', 'met', 'Lisa', ',', 'a', 'data', 'scientist', 'who', 'specialized', 'in', 'machine', 'learning', '.', 'They', 'quickly', 'bonded', 'over', 'their', 'shared', 'passion', 'for', 'AI', 'and', 'robotics', '.', 'Together', ',', '

Stemmimng example

In [8]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [9]:
stemmer = PorterStemmer()

In [10]:
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] = ' '.join(words)

In [11]:
print(sentences)

['john alway fascin technolog .', 'ever sinc child , dream becom softwar engin .', 'after year studi hard work , final land job well-known tech compani , techcorp .', 'hi first project develop ai-bas system could analyz custom feedback provid real-tim insight .', "excit nervou time , john knew opportun wait . ''", '`` one day , take break , john met lisa , data scientist special machin learn .', 'they quickli bond share passion ai robot .', "togeth , brainstorm innov idea could revolution compani 's product .", "their combin effort soon paid , ai system becam one compani 's top-perform tool . ''", '`` as month pass , john found think start tech startup .', 'he knew risk involv felt potenti reward far outweigh .', "with lisa 's encourag support close colleagu , john decid take leap begin entrepreneuri journey ."]


Lemmatization

In [12]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [15]:
sentences = nltk.sent_tokenize(paragraph)
lemmatizer = WordNetLemmatizer()

In [16]:
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] = ' '.join(words)

print(sentences)

['John always fascinated technology .', 'Ever since child , dreamed becoming software engineer .', 'After year studying hard work , finally landed job well-known tech company , TechCorp .', 'His first project develop AI-based system could analyze customer feedback provide real-time insight .', "Excited nervous time , John knew opportunity waiting . ''", '`` One day , taking break , John met Lisa , data scientist specialized machine learning .', 'They quickly bonded shared passion AI robotics .', "Together , brainstormed innovative idea could revolutionize company 's product .", "Their combined effort soon paid , AI system became one company 's top-performing tool . ''", '`` As month passed , John found thinking starting tech startup .', 'He knew risk involved felt potential reward far outweighed .', "With Lisa 's encouragement support close colleague , John decided take leap begin entrepreneurial journey ."]


Bag of Words

In [17]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer                                                                                                     

In [18]:
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
new_sentences = []


In [20]:
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]',' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review =' '.join(review)
    new_sentences.append(review)


#print(review)
print(new_sentences)

lisa encouragement support close colleague john decided take leap begin entrepreneurial journey
['john always fascinated technology', 'ever since child dreamed becoming software engineer', 'year studying hard work finally landed job well known tech company techcorp', 'first project develop ai based system could analyze customer feedback provide real time insight', 'excited nervous time john knew opportunity waiting', 'one day taking break john met lisa data scientist specialized machine learning', 'quickly bonded shared passion ai robotics', 'together brainstormed innovative idea could revolutionize company product', 'combined effort soon paid ai system became one company top performing tool', 'month passed john found thinking starting tech startup', 'knew risk involved felt potential reward far outweighed', 'lisa encouragement support close colleague john decided take leap begin entrepreneurial journey', 'john always fascinated technology', 'ever since child dreamed becoming software 

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()
x= cv.fit_transform(new_sentences).toarray()
print(x)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


TF -IDF (Term Frequency - Inverse Document Frequency)

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
y = tf.fit_transform(new_sentences).toarray()
print(y)

[[0.         0.54712758 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.29840749 0.29840749 0.29840749]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [1]:
# Import necessary libraries
import torch
import torch.nn as nn
from torch.nn.functional import pad
import numpy as np

# Sample sentences
sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

# Vocabulary size
vocab_size = 10000

# One-hot encoding function
def one_hot_encoding(sentences, vocab_size):
    word2index = {word: idx for idx, word in enumerate(set(" ".join(sentences).split()))}
    onehot_repr = [[word2index[word] % vocab_size for word in sentence.split()] for sentence in sentences]
    return onehot_repr

# One-hot encoding representation
onehot_repr = one_hot_encoding(sentences, vocab_size)
print("One-hot Encoded Representation:", onehot_repr)

# Pad sequences to ensure each sequence has the same length
sentence_length = 8
padded_docs = [np.pad(doc, (sentence_length - len(doc), 0), 'constant', constant_values=0) for doc in onehot_repr]
padded_docs = torch.tensor(padded_docs)
print("Padded Sequences:\n", padded_docs)

# Embedding layer parameters
embedding_dim = 10

# Define PyTorch model with an Embedding layer
class EmbeddingModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, sentence_length):
        super(EmbeddingModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.sentence_length = sentence_length

    def forward(self, x):
        embedded = self.embedding(x)
        return embedded

# Initialize and summarize the model
model = EmbeddingModel(vocab_size, embedding_dim, sentence_length)
print(model)

# Generate embeddings
embedded_output = model(padded_docs)
print("Embedded Output:\n", embedded_output)


One-hot Encoded Representation: [[17, 5, 15, 8], [17, 5, 15, 1], [17, 12, 15, 3], [13, 11, 10, 14, 7], [13, 11, 10, 14, 16], [2, 17, 9, 15, 0], [4, 6, 18, 14]]


C:\Users\Sriparna\AppData\Local\Temp\ipykernel_15164\3808972963.py:34: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:277.)
  padded_docs = torch.tensor(padded_docs)


Padded Sequences:
 tensor([[ 0,  0,  0,  0, 17,  5, 15,  8],
        [ 0,  0,  0,  0, 17,  5, 15,  1],
        [ 0,  0,  0,  0, 17, 12, 15,  3],
        [ 0,  0,  0, 13, 11, 10, 14,  7],
        [ 0,  0,  0, 13, 11, 10, 14, 16],
        [ 0,  0,  0,  2, 17,  9, 15,  0],
        [ 0,  0,  0,  0,  4,  6, 18, 14]], dtype=torch.int32)
EmbeddingModel(
  (embedding): Embedding(10000, 10)
)
Embedded Output:
 tensor([[[-1.9109,  1.2603,  0.0902,  0.4615,  0.6784,  0.2136, -0.5116,
          -0.0304, -0.3281, -0.4420],
         [-1.9109,  1.2603,  0.0902,  0.4615,  0.6784,  0.2136, -0.5116,
          -0.0304, -0.3281, -0.4420],
         [-1.9109,  1.2603,  0.0902,  0.4615,  0.6784,  0.2136, -0.5116,
          -0.0304, -0.3281, -0.4420],
         [-1.9109,  1.2603,  0.0902,  0.4615,  0.6784,  0.2136, -0.5116,
          -0.0304, -0.3281, -0.4420],
         [-0.4542,  0.1029, -0.3196, -1.7591,  0.9019, -0.7763,  0.4036,
           0.2324, -1.3783, -1.2706],
         [ 0.7639, -0.7502, -0.5962, -0.